//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFC_Tools.TiptopService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TiptopService.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: 消息 QueryMateriaMasterRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryMateriaMaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.QueryMateriaMasterResponse QueryMateriaMaster(SFC_Tools.TiptopService.QueryMateriaMasterRequest request);
        
        // CODEGEN: 消息 QueryMateriaMaster1Request 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryMateriaMaster1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.QueryMateriaMaster1Response QueryMateriaMaster1(SFC_Tools.TiptopService.QueryMateriaMaster1Request request);
        
        // CODEGEN: 消息 QueryMateriaMaster2Request 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryMateriaMaster2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.QueryMateriaMaster2Response QueryMateriaMaster2(SFC_Tools.TiptopService.QueryMateriaMaster2Request request);
        
        // CODEGEN: 消息 QueryStockRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryStock", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.QueryStockResponse QueryStock(SFC_Tools.TiptopService.QueryStockRequest request);
        
        // CODEGEN: 消息 QueryStock1Request 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryStock1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.QueryStock1Response QueryStock1(SFC_Tools.TiptopService.QueryStock1Request request);
        
        // CODEGEN: 消息 QueryBomRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryBom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.QueryBomResponse QueryBom(SFC_Tools.TiptopService.QueryBomRequest request);
        
        // CODEGEN: 消息 QueryBom1Request 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryBom1", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.QueryBom1Response QueryBom1(SFC_Tools.TiptopService.QueryBom1Request request);
        
        // CODEGEN: 消息 QueryBom2Request 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryBom2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.QueryBom2Response QueryBom2(SFC_Tools.TiptopService.QueryBom2Request request);
        
        // CODEGEN: 消息 GoodsTransferBillRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GoodsTransferBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.GoodsTransferBillResponse GoodsTransferBill(SFC_Tools.TiptopService.GoodsTransferBillRequest request);
        
        // CODEGEN: 消息 GoodsBillDownloadRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GoodsBillDownload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.GoodsBillDownloadResponse GoodsBillDownload(SFC_Tools.TiptopService.GoodsBillDownloadRequest request);
        
        // CODEGEN: 消息 ChargeBillRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.ChargeBillResponse ChargeBill(SFC_Tools.TiptopService.ChargeBillRequest request);
        
        // CODEGEN: 消息 ChargeReturnBillRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChargeReturnBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.ChargeReturnBillResponse ChargeReturnBill(SFC_Tools.TiptopService.ChargeReturnBillRequest request);
        
        // CODEGEN: 消息 QueryWorkOrderRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/QueryWorkOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.QueryWorkOrderResponse QueryWorkOrder(SFC_Tools.TiptopService.QueryWorkOrderRequest request);
        
        // CODEGEN: 消息 GoodsBillRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GoodsBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.GoodsBillResponse GoodsBill(SFC_Tools.TiptopService.GoodsBillRequest request);
        
        // CODEGEN: 消息 GoodsReturnBillRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GoodsReturnBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.GoodsReturnBillResponse GoodsReturnBill(SFC_Tools.TiptopService.GoodsReturnBillRequest request);
        
        // CODEGEN: 消息 FinishedGoodsBillRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FinishedGoodsBill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.FinishedGoodsBillResponse FinishedGoodsBill(SFC_Tools.TiptopService.FinishedGoodsBillRequest request);
        
        // CODEGEN: 消息 CloseWorkOrderRequest 以后生成的消息协定具有标头
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CloseWorkOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.CloseWorkOrderResponse CloseWorkOrder(SFC_Tools.TiptopService.CloseWorkOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateWorkOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.TiptopService.ServiceOut CreateWorkOrder(string Client, string BillHead, string DeptCode, string PartNo, decimal Qty, System.DateTime StartDate, System.DateTime EndDate);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TPSoap : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIDField;
        
        private string userPWDField;
        
        private string ipAddressField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserPWD {
            get {
                return this.userPWDField;
            }
            set {
                this.userPWDField = value;
                this.RaisePropertyChanged("UserPWD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IpAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
                this.RaisePropertyChanged("IpAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BackRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] arrstrresField;
        
        private System.Data.DataTable workorderdetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] arrstrres {
            get {
                return this.arrstrresField;
            }
            set {
                this.arrstrresField = value;
                this.RaisePropertyChanged("arrstrres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Data.DataTable workorderdetail {
            get {
                return this.workorderdetailField;
            }
            set {
                this.workorderdetailField = value;
                this.RaisePropertyChanged("workorderdetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceOut : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BackRes backresField;
        
        private string statusField;
        
        private System.Data.DataTable tableInfoField;
        
        private System.Data.DataSet setInfoField;
        
        private string[] arrayInfoField;
        
        private string messageField;
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BackRes Backres {
            get {
                return this.backresField;
            }
            set {
                this.backresField = value;
                this.RaisePropertyChanged("Backres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Data.DataTable TableInfo {
            get {
                return this.tableInfoField;
            }
            set {
                this.tableInfoField = value;
                this.RaisePropertyChanged("TableInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Data.DataSet SetInfo {
            get {
                return this.setInfoField;
            }
            set {
                this.setInfoField = value;
                this.RaisePropertyChanged("SetInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public string[] ArrayInfo {
            get {
                return this.arrayInfoField;
            }
            set {
                this.arrayInfoField = value;
                this.RaisePropertyChanged("ArrayInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryMateriaMaster", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryMateriaMasterRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        public QueryMateriaMasterRequest() {
        }
        
        public QueryMateriaMasterRequest(SFC_Tools.TiptopService.TPSoap TPSoap, string Client) {
            this.TPSoap = TPSoap;
            this.Client = Client;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryMateriaMasterResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryMateriaMasterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut QueryMateriaMasterResult;
        
        public QueryMateriaMasterResponse() {
        }
        
        public QueryMateriaMasterResponse(SFC_Tools.TiptopService.ServiceOut QueryMateriaMasterResult) {
            this.QueryMateriaMasterResult = QueryMateriaMasterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryMateriaMaster1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryMateriaMaster1Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime dtbegin;
        
        public QueryMateriaMaster1Request() {
        }
        
        public QueryMateriaMaster1Request(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, System.DateTime dtbegin) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.dtbegin = dtbegin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryMateriaMaster1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryMateriaMaster1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut QueryMateriaMaster1Result;
        
        public QueryMateriaMaster1Response() {
        }
        
        public QueryMateriaMaster1Response(SFC_Tools.TiptopService.ServiceOut QueryMateriaMaster1Result) {
            this.QueryMateriaMaster1Result = QueryMateriaMaster1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryMateriaMaster2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryMateriaMaster2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string PartNo;
        
        public QueryMateriaMaster2Request() {
        }
        
        public QueryMateriaMaster2Request(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string PartNo) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.PartNo = PartNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryMateriaMaster2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryMateriaMaster2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut QueryMateriaMaster2Result;
        
        public QueryMateriaMaster2Response() {
        }
        
        public QueryMateriaMaster2Response(SFC_Tools.TiptopService.ServiceOut QueryMateriaMaster2Result) {
            this.QueryMateriaMaster2Result = QueryMateriaMaster2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryStock", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryStockRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string warehouse;
        
        public QueryStockRequest() {
        }
        
        public QueryStockRequest(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string warehouse) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.warehouse = warehouse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryStockResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryStockResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut QueryStockResult;
        
        public QueryStockResponse() {
        }
        
        public QueryStockResponse(SFC_Tools.TiptopService.ServiceOut QueryStockResult) {
            this.QueryStockResult = QueryStockResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryStock1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryStock1Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string warehouse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string partno;
        
        public QueryStock1Request() {
        }
        
        public QueryStock1Request(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string warehouse, string partno) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.warehouse = warehouse;
            this.partno = partno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryStock1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryStock1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut QueryStock1Result;
        
        public QueryStock1Response() {
        }
        
        public QueryStock1Response(SFC_Tools.TiptopService.ServiceOut QueryStock1Result) {
            this.QueryStock1Result = QueryStock1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryBom", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryBomRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        public QueryBomRequest() {
        }
        
        public QueryBomRequest(SFC_Tools.TiptopService.TPSoap TPSoap, string Client) {
            this.TPSoap = TPSoap;
            this.Client = Client;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryBomResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryBomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut QueryBomResult;
        
        public QueryBomResponse() {
        }
        
        public QueryBomResponse(SFC_Tools.TiptopService.ServiceOut QueryBomResult) {
            this.QueryBomResult = QueryBomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryBom1", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryBom1Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime dtbegin;
        
        public QueryBom1Request() {
        }
        
        public QueryBom1Request(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, System.DateTime dtbegin) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.dtbegin = dtbegin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryBom1Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryBom1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut QueryBom1Result;
        
        public QueryBom1Response() {
        }
        
        public QueryBom1Response(SFC_Tools.TiptopService.ServiceOut QueryBom1Result) {
            this.QueryBom1Result = QueryBom1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryBom2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryBom2Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pn;
        
        public QueryBom2Request() {
        }
        
        public QueryBom2Request(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string pn) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.pn = pn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryBom2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryBom2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut QueryBom2Result;
        
        public QueryBom2Response() {
        }
        
        public QueryBom2Response(SFC_Tools.TiptopService.ServiceOut QueryBom2Result) {
            this.QueryBom2Result = QueryBom2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GoodsTransferBill", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GoodsTransferBillRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string BillHead;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime BillDate;
        
        public GoodsTransferBillRequest() {
        }
        
        public GoodsTransferBillRequest(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, System.DateTime BillDate) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.BillHead = BillHead;
            this.BillDate = BillDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GoodsTransferBillResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GoodsTransferBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut GoodsTransferBillResult;
        
        public GoodsTransferBillResponse() {
        }
        
        public GoodsTransferBillResponse(SFC_Tools.TiptopService.ServiceOut GoodsTransferBillResult) {
            this.GoodsTransferBillResult = GoodsTransferBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GoodsBillDownload", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GoodsBillDownloadRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string BillHead;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime BillDate;
        
        public GoodsBillDownloadRequest() {
        }
        
        public GoodsBillDownloadRequest(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, System.DateTime BillDate) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.BillHead = BillHead;
            this.BillDate = BillDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GoodsBillDownloadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GoodsBillDownloadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut GoodsBillDownloadResult;
        
        public GoodsBillDownloadResponse() {
        }
        
        public GoodsBillDownloadResponse(SFC_Tools.TiptopService.ServiceOut GoodsBillDownloadResult) {
            this.GoodsBillDownloadResult = GoodsBillDownloadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeBill", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChargeBillRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string BillHead;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime BillDate;
        
        public ChargeBillRequest() {
        }
        
        public ChargeBillRequest(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, System.DateTime BillDate) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.BillHead = BillHead;
            this.BillDate = BillDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeBillResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChargeBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut ChargeBillResult;
        
        public ChargeBillResponse() {
        }
        
        public ChargeBillResponse(SFC_Tools.TiptopService.ServiceOut ChargeBillResult) {
            this.ChargeBillResult = ChargeBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeReturnBill", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChargeReturnBillRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string BillHead;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.DateTime BillDate;
        
        public ChargeReturnBillRequest() {
        }
        
        public ChargeReturnBillRequest(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, System.DateTime BillDate) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.BillHead = BillHead;
            this.BillDate = BillDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChargeReturnBillResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChargeReturnBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut ChargeReturnBillResult;
        
        public ChargeReturnBillResponse() {
        }
        
        public ChargeReturnBillResponse(SFC_Tools.TiptopService.ServiceOut ChargeReturnBillResult) {
            this.ChargeReturnBillResult = ChargeReturnBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryWorkOrder", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryWorkOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string WorkOrder;
        
        public QueryWorkOrderRequest() {
        }
        
        public QueryWorkOrderRequest(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string WorkOrder) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.WorkOrder = WorkOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryWorkOrderResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class QueryWorkOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut QueryWorkOrderResult;
        
        public QueryWorkOrderResponse() {
        }
        
        public QueryWorkOrderResponse(SFC_Tools.TiptopService.ServiceOut QueryWorkOrderResult) {
            this.QueryWorkOrderResult = QueryWorkOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GoodsBill", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GoodsBillRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string BillHead;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string WorkOrder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string PartNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public decimal Qty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Warehouse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Bin;
        
        public GoodsBillRequest() {
        }
        
        public GoodsBillRequest(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.BillHead = BillHead;
            this.WorkOrder = WorkOrder;
            this.PartNo = PartNo;
            this.Qty = Qty;
            this.Warehouse = Warehouse;
            this.Bin = Bin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GoodsBillResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GoodsBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut GoodsBillResult;
        
        public GoodsBillResponse() {
        }
        
        public GoodsBillResponse(SFC_Tools.TiptopService.ServiceOut GoodsBillResult) {
            this.GoodsBillResult = GoodsBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GoodsReturnBill", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GoodsReturnBillRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string BillHead;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string WorkOrder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string PartNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public decimal Qty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Warehouse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Bin;
        
        public GoodsReturnBillRequest() {
        }
        
        public GoodsReturnBillRequest(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.BillHead = BillHead;
            this.WorkOrder = WorkOrder;
            this.PartNo = PartNo;
            this.Qty = Qty;
            this.Warehouse = Warehouse;
            this.Bin = Bin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GoodsReturnBillResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GoodsReturnBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut GoodsReturnBillResult;
        
        public GoodsReturnBillResponse() {
        }
        
        public GoodsReturnBillResponse(SFC_Tools.TiptopService.ServiceOut GoodsReturnBillResult) {
            this.GoodsReturnBillResult = GoodsReturnBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FinishedGoodsBill", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FinishedGoodsBillRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string BillHead;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string WorkOrder;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string PartNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public decimal Qty;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string Warehouse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string Bin;
        
        public FinishedGoodsBillRequest() {
        }
        
        public FinishedGoodsBillRequest(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.BillHead = BillHead;
            this.WorkOrder = WorkOrder;
            this.PartNo = PartNo;
            this.Qty = Qty;
            this.Warehouse = Warehouse;
            this.Bin = Bin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FinishedGoodsBillResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FinishedGoodsBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut FinishedGoodsBillResult;
        
        public FinishedGoodsBillResponse() {
        }
        
        public FinishedGoodsBillResponse(SFC_Tools.TiptopService.ServiceOut FinishedGoodsBillResult) {
            this.FinishedGoodsBillResult = FinishedGoodsBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CloseWorkOrder", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CloseWorkOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.TiptopService.TPSoap TPSoap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Client;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string WorkOrder;
        
        public CloseWorkOrderRequest() {
        }
        
        public CloseWorkOrderRequest(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string WorkOrder) {
            this.TPSoap = TPSoap;
            this.Client = Client;
            this.WorkOrder = WorkOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CloseWorkOrderResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CloseWorkOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.TiptopService.ServiceOut CloseWorkOrderResult;
        
        public CloseWorkOrderResponse() {
        }
        
        public CloseWorkOrderResponse(SFC_Tools.TiptopService.ServiceOut CloseWorkOrderResult) {
            this.CloseWorkOrderResult = CloseWorkOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : SFC_Tools.TiptopService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<SFC_Tools.TiptopService.Service1Soap>, SFC_Tools.TiptopService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.QueryMateriaMasterResponse SFC_Tools.TiptopService.Service1Soap.QueryMateriaMaster(SFC_Tools.TiptopService.QueryMateriaMasterRequest request) {
            return base.Channel.QueryMateriaMaster(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut QueryMateriaMaster(SFC_Tools.TiptopService.TPSoap TPSoap, string Client) {
            SFC_Tools.TiptopService.QueryMateriaMasterRequest inValue = new SFC_Tools.TiptopService.QueryMateriaMasterRequest();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            SFC_Tools.TiptopService.QueryMateriaMasterResponse retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).QueryMateriaMaster(inValue);
            return retVal.QueryMateriaMasterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.QueryMateriaMaster1Response SFC_Tools.TiptopService.Service1Soap.QueryMateriaMaster1(SFC_Tools.TiptopService.QueryMateriaMaster1Request request) {
            return base.Channel.QueryMateriaMaster1(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut QueryMateriaMaster1(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, System.DateTime dtbegin) {
            SFC_Tools.TiptopService.QueryMateriaMaster1Request inValue = new SFC_Tools.TiptopService.QueryMateriaMaster1Request();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.dtbegin = dtbegin;
            SFC_Tools.TiptopService.QueryMateriaMaster1Response retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).QueryMateriaMaster1(inValue);
            return retVal.QueryMateriaMaster1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.QueryMateriaMaster2Response SFC_Tools.TiptopService.Service1Soap.QueryMateriaMaster2(SFC_Tools.TiptopService.QueryMateriaMaster2Request request) {
            return base.Channel.QueryMateriaMaster2(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut QueryMateriaMaster2(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string PartNo) {
            SFC_Tools.TiptopService.QueryMateriaMaster2Request inValue = new SFC_Tools.TiptopService.QueryMateriaMaster2Request();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.PartNo = PartNo;
            SFC_Tools.TiptopService.QueryMateriaMaster2Response retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).QueryMateriaMaster2(inValue);
            return retVal.QueryMateriaMaster2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.QueryStockResponse SFC_Tools.TiptopService.Service1Soap.QueryStock(SFC_Tools.TiptopService.QueryStockRequest request) {
            return base.Channel.QueryStock(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut QueryStock(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string warehouse) {
            SFC_Tools.TiptopService.QueryStockRequest inValue = new SFC_Tools.TiptopService.QueryStockRequest();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.warehouse = warehouse;
            SFC_Tools.TiptopService.QueryStockResponse retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).QueryStock(inValue);
            return retVal.QueryStockResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.QueryStock1Response SFC_Tools.TiptopService.Service1Soap.QueryStock1(SFC_Tools.TiptopService.QueryStock1Request request) {
            return base.Channel.QueryStock1(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut QueryStock1(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string warehouse, string partno) {
            SFC_Tools.TiptopService.QueryStock1Request inValue = new SFC_Tools.TiptopService.QueryStock1Request();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.warehouse = warehouse;
            inValue.partno = partno;
            SFC_Tools.TiptopService.QueryStock1Response retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).QueryStock1(inValue);
            return retVal.QueryStock1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.QueryBomResponse SFC_Tools.TiptopService.Service1Soap.QueryBom(SFC_Tools.TiptopService.QueryBomRequest request) {
            return base.Channel.QueryBom(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut QueryBom(SFC_Tools.TiptopService.TPSoap TPSoap, string Client) {
            SFC_Tools.TiptopService.QueryBomRequest inValue = new SFC_Tools.TiptopService.QueryBomRequest();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            SFC_Tools.TiptopService.QueryBomResponse retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).QueryBom(inValue);
            return retVal.QueryBomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.QueryBom1Response SFC_Tools.TiptopService.Service1Soap.QueryBom1(SFC_Tools.TiptopService.QueryBom1Request request) {
            return base.Channel.QueryBom1(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut QueryBom1(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, System.DateTime dtbegin) {
            SFC_Tools.TiptopService.QueryBom1Request inValue = new SFC_Tools.TiptopService.QueryBom1Request();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.dtbegin = dtbegin;
            SFC_Tools.TiptopService.QueryBom1Response retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).QueryBom1(inValue);
            return retVal.QueryBom1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.QueryBom2Response SFC_Tools.TiptopService.Service1Soap.QueryBom2(SFC_Tools.TiptopService.QueryBom2Request request) {
            return base.Channel.QueryBom2(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut QueryBom2(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string pn) {
            SFC_Tools.TiptopService.QueryBom2Request inValue = new SFC_Tools.TiptopService.QueryBom2Request();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.pn = pn;
            SFC_Tools.TiptopService.QueryBom2Response retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).QueryBom2(inValue);
            return retVal.QueryBom2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.GoodsTransferBillResponse SFC_Tools.TiptopService.Service1Soap.GoodsTransferBill(SFC_Tools.TiptopService.GoodsTransferBillRequest request) {
            return base.Channel.GoodsTransferBill(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut GoodsTransferBill(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, System.DateTime BillDate) {
            SFC_Tools.TiptopService.GoodsTransferBillRequest inValue = new SFC_Tools.TiptopService.GoodsTransferBillRequest();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.BillHead = BillHead;
            inValue.BillDate = BillDate;
            SFC_Tools.TiptopService.GoodsTransferBillResponse retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).GoodsTransferBill(inValue);
            return retVal.GoodsTransferBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.GoodsBillDownloadResponse SFC_Tools.TiptopService.Service1Soap.GoodsBillDownload(SFC_Tools.TiptopService.GoodsBillDownloadRequest request) {
            return base.Channel.GoodsBillDownload(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut GoodsBillDownload(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, System.DateTime BillDate) {
            SFC_Tools.TiptopService.GoodsBillDownloadRequest inValue = new SFC_Tools.TiptopService.GoodsBillDownloadRequest();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.BillHead = BillHead;
            inValue.BillDate = BillDate;
            SFC_Tools.TiptopService.GoodsBillDownloadResponse retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).GoodsBillDownload(inValue);
            return retVal.GoodsBillDownloadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.ChargeBillResponse SFC_Tools.TiptopService.Service1Soap.ChargeBill(SFC_Tools.TiptopService.ChargeBillRequest request) {
            return base.Channel.ChargeBill(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut ChargeBill(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, System.DateTime BillDate) {
            SFC_Tools.TiptopService.ChargeBillRequest inValue = new SFC_Tools.TiptopService.ChargeBillRequest();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.BillHead = BillHead;
            inValue.BillDate = BillDate;
            SFC_Tools.TiptopService.ChargeBillResponse retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).ChargeBill(inValue);
            return retVal.ChargeBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.ChargeReturnBillResponse SFC_Tools.TiptopService.Service1Soap.ChargeReturnBill(SFC_Tools.TiptopService.ChargeReturnBillRequest request) {
            return base.Channel.ChargeReturnBill(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut ChargeReturnBill(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, System.DateTime BillDate) {
            SFC_Tools.TiptopService.ChargeReturnBillRequest inValue = new SFC_Tools.TiptopService.ChargeReturnBillRequest();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.BillHead = BillHead;
            inValue.BillDate = BillDate;
            SFC_Tools.TiptopService.ChargeReturnBillResponse retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).ChargeReturnBill(inValue);
            return retVal.ChargeReturnBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.QueryWorkOrderResponse SFC_Tools.TiptopService.Service1Soap.QueryWorkOrder(SFC_Tools.TiptopService.QueryWorkOrderRequest request) {
            return base.Channel.QueryWorkOrder(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut QueryWorkOrder(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string WorkOrder) {
            SFC_Tools.TiptopService.QueryWorkOrderRequest inValue = new SFC_Tools.TiptopService.QueryWorkOrderRequest();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.WorkOrder = WorkOrder;
            SFC_Tools.TiptopService.QueryWorkOrderResponse retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).QueryWorkOrder(inValue);
            return retVal.QueryWorkOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.GoodsBillResponse SFC_Tools.TiptopService.Service1Soap.GoodsBill(SFC_Tools.TiptopService.GoodsBillRequest request) {
            return base.Channel.GoodsBill(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut GoodsBill(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin) {
            SFC_Tools.TiptopService.GoodsBillRequest inValue = new SFC_Tools.TiptopService.GoodsBillRequest();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.BillHead = BillHead;
            inValue.WorkOrder = WorkOrder;
            inValue.PartNo = PartNo;
            inValue.Qty = Qty;
            inValue.Warehouse = Warehouse;
            inValue.Bin = Bin;
            SFC_Tools.TiptopService.GoodsBillResponse retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).GoodsBill(inValue);
            return retVal.GoodsBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.GoodsReturnBillResponse SFC_Tools.TiptopService.Service1Soap.GoodsReturnBill(SFC_Tools.TiptopService.GoodsReturnBillRequest request) {
            return base.Channel.GoodsReturnBill(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut GoodsReturnBill(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin) {
            SFC_Tools.TiptopService.GoodsReturnBillRequest inValue = new SFC_Tools.TiptopService.GoodsReturnBillRequest();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.BillHead = BillHead;
            inValue.WorkOrder = WorkOrder;
            inValue.PartNo = PartNo;
            inValue.Qty = Qty;
            inValue.Warehouse = Warehouse;
            inValue.Bin = Bin;
            SFC_Tools.TiptopService.GoodsReturnBillResponse retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).GoodsReturnBill(inValue);
            return retVal.GoodsReturnBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.FinishedGoodsBillResponse SFC_Tools.TiptopService.Service1Soap.FinishedGoodsBill(SFC_Tools.TiptopService.FinishedGoodsBillRequest request) {
            return base.Channel.FinishedGoodsBill(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut FinishedGoodsBill(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin) {
            SFC_Tools.TiptopService.FinishedGoodsBillRequest inValue = new SFC_Tools.TiptopService.FinishedGoodsBillRequest();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.BillHead = BillHead;
            inValue.WorkOrder = WorkOrder;
            inValue.PartNo = PartNo;
            inValue.Qty = Qty;
            inValue.Warehouse = Warehouse;
            inValue.Bin = Bin;
            SFC_Tools.TiptopService.FinishedGoodsBillResponse retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).FinishedGoodsBill(inValue);
            return retVal.FinishedGoodsBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.TiptopService.CloseWorkOrderResponse SFC_Tools.TiptopService.Service1Soap.CloseWorkOrder(SFC_Tools.TiptopService.CloseWorkOrderRequest request) {
            return base.Channel.CloseWorkOrder(request);
        }
        
        public SFC_Tools.TiptopService.ServiceOut CloseWorkOrder(SFC_Tools.TiptopService.TPSoap TPSoap, string Client, string WorkOrder) {
            SFC_Tools.TiptopService.CloseWorkOrderRequest inValue = new SFC_Tools.TiptopService.CloseWorkOrderRequest();
            inValue.TPSoap = TPSoap;
            inValue.Client = Client;
            inValue.WorkOrder = WorkOrder;
            SFC_Tools.TiptopService.CloseWorkOrderResponse retVal = ((SFC_Tools.TiptopService.Service1Soap)(this)).CloseWorkOrder(inValue);
            return retVal.CloseWorkOrderResult;
        }
        
        public SFC_Tools.TiptopService.ServiceOut CreateWorkOrder(string Client, string BillHead, string DeptCode, string PartNo, decimal Qty, System.DateTime StartDate, System.DateTime EndDate) {
            return base.Channel.CreateWorkOrder(Client, BillHead, DeptCode, PartNo, Qty, StartDate, EndDate);
        }
    }
}
