//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFC_Tools.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.MessagingSoap")]
    public interface MessagingSoap {
        
        // CODEGEN: Generating message contract since message SendOCMessageRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOCMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.ServiceReference1.SendOCMessageResponse SendOCMessage(SFC_Tools.ServiceReference1.SendOCMessageRequest request);
        
        // CODEGEN: Generating message contract since message SendSMSMessageRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.ServiceReference1.SendSMSMessageResponse SendSMSMessage(SFC_Tools.ServiceReference1.SendSMSMessageRequest request);
        
        // CODEGEN: Generating message contract since message SendFormatSMSMessageRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendFormatSMSMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.ServiceReference1.SendFormatSMSMessageResponse SendFormatSMSMessage(SFC_Tools.ServiceReference1.SendFormatSMSMessageRequest request);
        
        // CODEGEN: Generating message contract since message ReceiveSMSMessageRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveSMSMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.ServiceReference1.ReceiveSMSMessageResponse ReceiveSMSMessage(SFC_Tools.ServiceReference1.ReceiveSMSMessageRequest request);
        
        // CODEGEN: Generating message contract since message GetAttachmentRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAttachment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.ServiceReference1.GetAttachmentResponse GetAttachment(SFC_Tools.ServiceReference1.GetAttachmentRequest request);
        
        // CODEGEN: Generating message contract since message GetOcUserStateRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOcUserState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.ServiceReference1.GetOcUserStateResponse GetOcUserState(SFC_Tools.ServiceReference1.GetOcUserStateRequest request);
        
        // CODEGEN: Generating message contract since message GetSendingMessageStatusByTokenRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSendingMessageStatusByToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.ServiceReference1.GetSendingMessageStatusByTokenResponse GetSendingMessageStatusByToken(SFC_Tools.ServiceReference1.GetSendingMessageStatusByTokenRequest request);
        
        // CODEGEN: Generating message contract since message SendGroupMailsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendGroupMails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.ServiceReference1.SendGroupMailsResponse SendGroupMails(SFC_Tools.ServiceReference1.SendGroupMailsRequest request);
        
        // CODEGEN: Generating message contract since message SendGroupMailsWithAttachmentsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendGroupMailsWithAttachments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SFC_Tools.ServiceReference1.SendGroupMailsWithAttachmentsResponse SendGroupMailsWithAttachments(SFC_Tools.ServiceReference1.SendGroupMailsWithAttachmentsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationSoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userIdField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Attachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIdField;
        
        private string fileNameField;
        
        private string contentBase64StringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("FileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ContentBase64String {
            get {
                return this.contentBase64StringField;
            }
            set {
                this.contentBase64StringField = value;
                this.RaisePropertyChanged("ContentBase64String");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SmsMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msgIDField;
        
        private string fromField;
        
        private string toField;
        
        private string contentField;
        
        private string receiveDateTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
                this.RaisePropertyChanged("MsgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("Content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReceiveDateTime {
            get {
                return this.receiveDateTimeField;
            }
            set {
                this.receiveDateTimeField = value;
                this.RaisePropertyChanged("ReceiveDateTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOCMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOCMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ocAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string toOC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string content;
        
        public SendOCMessageRequest() {
        }
        
        public SendOCMessageRequest(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string ocAccount, string password, string toOC, string content) {
            this.AuthenticationSoapHeader = AuthenticationSoapHeader;
            this.ocAccount = ocAccount;
            this.password = password;
            this.toOC = toOC;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendOCMessageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendOCMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] SendOCMessageResult;
        
        public SendOCMessageResponse() {
        }
        
        public SendOCMessageResponse(string[] SendOCMessageResult) {
            this.SendOCMessageResult = SendOCMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string smsAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string toPhone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string content;
        
        public SendSMSMessageRequest() {
        }
        
        public SendSMSMessageRequest(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string smsAccount, string password, string toPhone, string content) {
            this.AuthenticationSoapHeader = AuthenticationSoapHeader;
            this.smsAccount = smsAccount;
            this.password = password;
            this.toPhone = toPhone;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSMessageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] SendSMSMessageResult;
        
        public SendSMSMessageResponse() {
        }
        
        public SendSMSMessageResponse(string[] SendSMSMessageResult) {
            this.SendSMSMessageResult = SendSMSMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendFormatSMSMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendFormatSMSMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string smsAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string toPhone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string formatID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string[] content;
        
        public SendFormatSMSMessageRequest() {
        }
        
        public SendFormatSMSMessageRequest(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string smsAccount, string password, string toPhone, string formatID, string[] content) {
            this.AuthenticationSoapHeader = AuthenticationSoapHeader;
            this.smsAccount = smsAccount;
            this.password = password;
            this.toPhone = toPhone;
            this.formatID = formatID;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendFormatSMSMessageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendFormatSMSMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] SendFormatSMSMessageResult;
        
        public SendFormatSMSMessageResponse() {
        }
        
        public SendFormatSMSMessageResponse(string[] SendFormatSMSMessageResult) {
            this.SendFormatSMSMessageResult = SendFormatSMSMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveSMSMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReceiveSMSMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string smsAccount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public ReceiveSMSMessageRequest() {
        }
        
        public ReceiveSMSMessageRequest(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string smsAccount, string password) {
            this.AuthenticationSoapHeader = AuthenticationSoapHeader;
            this.smsAccount = smsAccount;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReceiveSMSMessageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReceiveSMSMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SmsMessage[] ReceiveSMSMessageResult;
        
        public ReceiveSMSMessageResponse() {
        }
        
        public ReceiveSMSMessageResponse(SmsMessage[] ReceiveSMSMessageResult) {
            this.ReceiveSMSMessageResult = ReceiveSMSMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttachment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttachmentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string msgId;
        
        public GetAttachmentRequest() {
        }
        
        public GetAttachmentRequest(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string msgId) {
            this.AuthenticationSoapHeader = AuthenticationSoapHeader;
            this.msgId = msgId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAttachmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAttachmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Attachment[] GetAttachmentResult;
        
        public GetAttachmentResponse() {
        }
        
        public GetAttachmentResponse(Attachment[] GetAttachmentResult) {
            this.GetAttachmentResult = GetAttachmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOcUserState", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOcUserStateRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sipUri;
        
        public GetOcUserStateRequest() {
        }
        
        public GetOcUserStateRequest(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string sipUri) {
            this.AuthenticationSoapHeader = AuthenticationSoapHeader;
            this.sipUri = sipUri;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetOcUserStateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetOcUserStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetOcUserStateResult;
        
        public GetOcUserStateResponse() {
        }
        
        public GetOcUserStateResponse(string GetOcUserStateResult) {
            this.GetOcUserStateResult = GetOcUserStateResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MessageStatus {
        
        /// <remarks/>
        UnSend,
        
        /// <remarks/>
        SendSuccess,
        
        /// <remarks/>
        SendFailure,
        
        /// <remarks/>
        None,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSendingMessageStatusByToken", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSendingMessageStatusByTokenRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string tokenId;
        
        public GetSendingMessageStatusByTokenRequest() {
        }
        
        public GetSendingMessageStatusByTokenRequest(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string tokenId) {
            this.AuthenticationSoapHeader = AuthenticationSoapHeader;
            this.tokenId = tokenId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSendingMessageStatusByTokenResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSendingMessageStatusByTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SFC_Tools.ServiceReference1.MessageStatus GetSendingMessageStatusByTokenResult;
        
        public GetSendingMessageStatusByTokenResponse() {
        }
        
        public GetSendingMessageStatusByTokenResponse(SFC_Tools.ServiceReference1.MessageStatus GetSendingMessageStatusByTokenResult) {
            this.GetSendingMessageStatusByTokenResult = GetSendingMessageStatusByTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendGroupMails", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendGroupMailsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string To;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Cc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SmtpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SmtpPassowrd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string SmtpAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string NoteAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string NotesPassword;
        
        public SendGroupMailsRequest() {
        }
        
        public SendGroupMailsRequest(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string To, string Cc, string Subject, string Body, string SmtpID, string SmtpPassowrd, string SmtpAddress, string NoteAddress, string NotesPassword) {
            this.AuthenticationSoapHeader = AuthenticationSoapHeader;
            this.To = To;
            this.Cc = Cc;
            this.Subject = Subject;
            this.Body = Body;
            this.SmtpID = SmtpID;
            this.SmtpPassowrd = SmtpPassowrd;
            this.SmtpAddress = SmtpAddress;
            this.NoteAddress = NoteAddress;
            this.NotesPassword = NotesPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendGroupMailsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendGroupMailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] SendGroupMailsResult;
        
        public SendGroupMailsResponse() {
        }
        
        public SendGroupMailsResponse(string[] SendGroupMailsResult) {
            this.SendGroupMailsResult = SendGroupMailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendGroupMailsWithAttachments", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendGroupMailsWithAttachmentsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string To;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Cc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public Attachment[] Attachments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string SmtpID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string SmtpPassowrd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string SmtpAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string NoteAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string NotesPassword;
        
        public SendGroupMailsWithAttachmentsRequest() {
        }
        
        public SendGroupMailsWithAttachmentsRequest(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string To, string Cc, string Subject, string Body, Attachment[] Attachments, string SmtpID, string SmtpPassowrd, string SmtpAddress, string NoteAddress, string NotesPassword) {
            this.AuthenticationSoapHeader = AuthenticationSoapHeader;
            this.To = To;
            this.Cc = Cc;
            this.Subject = Subject;
            this.Body = Body;
            this.Attachments = Attachments;
            this.SmtpID = SmtpID;
            this.SmtpPassowrd = SmtpPassowrd;
            this.SmtpAddress = SmtpAddress;
            this.NoteAddress = NoteAddress;
            this.NotesPassword = NotesPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendGroupMailsWithAttachmentsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendGroupMailsWithAttachmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string[] SendGroupMailsWithAttachmentsResult;
        
        public SendGroupMailsWithAttachmentsResponse() {
        }
        
        public SendGroupMailsWithAttachmentsResponse(string[] SendGroupMailsWithAttachmentsResult) {
            this.SendGroupMailsWithAttachmentsResult = SendGroupMailsWithAttachmentsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessagingSoapChannel : SFC_Tools.ServiceReference1.MessagingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessagingSoapClient : System.ServiceModel.ClientBase<SFC_Tools.ServiceReference1.MessagingSoap>, SFC_Tools.ServiceReference1.MessagingSoap {
        
        public MessagingSoapClient() {
        }
        
        public MessagingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessagingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessagingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.ServiceReference1.SendOCMessageResponse SFC_Tools.ServiceReference1.MessagingSoap.SendOCMessage(SFC_Tools.ServiceReference1.SendOCMessageRequest request) {
            return base.Channel.SendOCMessage(request);
        }
        
        public string[] SendOCMessage(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string ocAccount, string password, string toOC, string content) {
            SFC_Tools.ServiceReference1.SendOCMessageRequest inValue = new SFC_Tools.ServiceReference1.SendOCMessageRequest();
            inValue.AuthenticationSoapHeader = AuthenticationSoapHeader;
            inValue.ocAccount = ocAccount;
            inValue.password = password;
            inValue.toOC = toOC;
            inValue.content = content;
            SFC_Tools.ServiceReference1.SendOCMessageResponse retVal = ((SFC_Tools.ServiceReference1.MessagingSoap)(this)).SendOCMessage(inValue);
            return retVal.SendOCMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.ServiceReference1.SendSMSMessageResponse SFC_Tools.ServiceReference1.MessagingSoap.SendSMSMessage(SFC_Tools.ServiceReference1.SendSMSMessageRequest request) {
            return base.Channel.SendSMSMessage(request);
        }
        
        public string[] SendSMSMessage(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string smsAccount, string password, string toPhone, string content) {
            SFC_Tools.ServiceReference1.SendSMSMessageRequest inValue = new SFC_Tools.ServiceReference1.SendSMSMessageRequest();
            inValue.AuthenticationSoapHeader = AuthenticationSoapHeader;
            inValue.smsAccount = smsAccount;
            inValue.password = password;
            inValue.toPhone = toPhone;
            inValue.content = content;
            SFC_Tools.ServiceReference1.SendSMSMessageResponse retVal = ((SFC_Tools.ServiceReference1.MessagingSoap)(this)).SendSMSMessage(inValue);
            return retVal.SendSMSMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.ServiceReference1.SendFormatSMSMessageResponse SFC_Tools.ServiceReference1.MessagingSoap.SendFormatSMSMessage(SFC_Tools.ServiceReference1.SendFormatSMSMessageRequest request) {
            return base.Channel.SendFormatSMSMessage(request);
        }
        
        public string[] SendFormatSMSMessage(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string smsAccount, string password, string toPhone, string formatID, string[] content) {
            SFC_Tools.ServiceReference1.SendFormatSMSMessageRequest inValue = new SFC_Tools.ServiceReference1.SendFormatSMSMessageRequest();
            inValue.AuthenticationSoapHeader = AuthenticationSoapHeader;
            inValue.smsAccount = smsAccount;
            inValue.password = password;
            inValue.toPhone = toPhone;
            inValue.formatID = formatID;
            inValue.content = content;
            SFC_Tools.ServiceReference1.SendFormatSMSMessageResponse retVal = ((SFC_Tools.ServiceReference1.MessagingSoap)(this)).SendFormatSMSMessage(inValue);
            return retVal.SendFormatSMSMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.ServiceReference1.ReceiveSMSMessageResponse SFC_Tools.ServiceReference1.MessagingSoap.ReceiveSMSMessage(SFC_Tools.ServiceReference1.ReceiveSMSMessageRequest request) {
            return base.Channel.ReceiveSMSMessage(request);
        }
        
        public SmsMessage[] ReceiveSMSMessage(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string smsAccount, string password) {
            SFC_Tools.ServiceReference1.ReceiveSMSMessageRequest inValue = new SFC_Tools.ServiceReference1.ReceiveSMSMessageRequest();
            inValue.AuthenticationSoapHeader = AuthenticationSoapHeader;
            inValue.smsAccount = smsAccount;
            inValue.password = password;
            SFC_Tools.ServiceReference1.ReceiveSMSMessageResponse retVal = ((SFC_Tools.ServiceReference1.MessagingSoap)(this)).ReceiveSMSMessage(inValue);
            return retVal.ReceiveSMSMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.ServiceReference1.GetAttachmentResponse SFC_Tools.ServiceReference1.MessagingSoap.GetAttachment(SFC_Tools.ServiceReference1.GetAttachmentRequest request) {
            return base.Channel.GetAttachment(request);
        }
        
        public Attachment[] GetAttachment(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string msgId) {
            SFC_Tools.ServiceReference1.GetAttachmentRequest inValue = new SFC_Tools.ServiceReference1.GetAttachmentRequest();
            inValue.AuthenticationSoapHeader = AuthenticationSoapHeader;
            inValue.msgId = msgId;
            SFC_Tools.ServiceReference1.GetAttachmentResponse retVal = ((SFC_Tools.ServiceReference1.MessagingSoap)(this)).GetAttachment(inValue);
            return retVal.GetAttachmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.ServiceReference1.GetOcUserStateResponse SFC_Tools.ServiceReference1.MessagingSoap.GetOcUserState(SFC_Tools.ServiceReference1.GetOcUserStateRequest request) {
            return base.Channel.GetOcUserState(request);
        }
        
        public string GetOcUserState(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string sipUri) {
            SFC_Tools.ServiceReference1.GetOcUserStateRequest inValue = new SFC_Tools.ServiceReference1.GetOcUserStateRequest();
            inValue.AuthenticationSoapHeader = AuthenticationSoapHeader;
            inValue.sipUri = sipUri;
            SFC_Tools.ServiceReference1.GetOcUserStateResponse retVal = ((SFC_Tools.ServiceReference1.MessagingSoap)(this)).GetOcUserState(inValue);
            return retVal.GetOcUserStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.ServiceReference1.GetSendingMessageStatusByTokenResponse SFC_Tools.ServiceReference1.MessagingSoap.GetSendingMessageStatusByToken(SFC_Tools.ServiceReference1.GetSendingMessageStatusByTokenRequest request) {
            return base.Channel.GetSendingMessageStatusByToken(request);
        }
        
        public SFC_Tools.ServiceReference1.MessageStatus GetSendingMessageStatusByToken(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string tokenId) {
            SFC_Tools.ServiceReference1.GetSendingMessageStatusByTokenRequest inValue = new SFC_Tools.ServiceReference1.GetSendingMessageStatusByTokenRequest();
            inValue.AuthenticationSoapHeader = AuthenticationSoapHeader;
            inValue.tokenId = tokenId;
            SFC_Tools.ServiceReference1.GetSendingMessageStatusByTokenResponse retVal = ((SFC_Tools.ServiceReference1.MessagingSoap)(this)).GetSendingMessageStatusByToken(inValue);
            return retVal.GetSendingMessageStatusByTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.ServiceReference1.SendGroupMailsResponse SFC_Tools.ServiceReference1.MessagingSoap.SendGroupMails(SFC_Tools.ServiceReference1.SendGroupMailsRequest request) {
            return base.Channel.SendGroupMails(request);
        }
        
        public string[] SendGroupMails(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string To, string Cc, string Subject, string Body, string SmtpID, string SmtpPassowrd, string SmtpAddress, string NoteAddress, string NotesPassword) {
            SFC_Tools.ServiceReference1.SendGroupMailsRequest inValue = new SFC_Tools.ServiceReference1.SendGroupMailsRequest();
            inValue.AuthenticationSoapHeader = AuthenticationSoapHeader;
            inValue.To = To;
            inValue.Cc = Cc;
            inValue.Subject = Subject;
            inValue.Body = Body;
            inValue.SmtpID = SmtpID;
            inValue.SmtpPassowrd = SmtpPassowrd;
            inValue.SmtpAddress = SmtpAddress;
            inValue.NoteAddress = NoteAddress;
            inValue.NotesPassword = NotesPassword;
            SFC_Tools.ServiceReference1.SendGroupMailsResponse retVal = ((SFC_Tools.ServiceReference1.MessagingSoap)(this)).SendGroupMails(inValue);
            return retVal.SendGroupMailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SFC_Tools.ServiceReference1.SendGroupMailsWithAttachmentsResponse SFC_Tools.ServiceReference1.MessagingSoap.SendGroupMailsWithAttachments(SFC_Tools.ServiceReference1.SendGroupMailsWithAttachmentsRequest request) {
            return base.Channel.SendGroupMailsWithAttachments(request);
        }
        
        public string[] SendGroupMailsWithAttachments(SFC_Tools.ServiceReference1.AuthenticationSoapHeader AuthenticationSoapHeader, string To, string Cc, string Subject, string Body, Attachment[] Attachments, string SmtpID, string SmtpPassowrd, string SmtpAddress, string NoteAddress, string NotesPassword) {
            SFC_Tools.ServiceReference1.SendGroupMailsWithAttachmentsRequest inValue = new SFC_Tools.ServiceReference1.SendGroupMailsWithAttachmentsRequest();
            inValue.AuthenticationSoapHeader = AuthenticationSoapHeader;
            inValue.To = To;
            inValue.Cc = Cc;
            inValue.Subject = Subject;
            inValue.Body = Body;
            inValue.Attachments = Attachments;
            inValue.SmtpID = SmtpID;
            inValue.SmtpPassowrd = SmtpPassowrd;
            inValue.SmtpAddress = SmtpAddress;
            inValue.NoteAddress = NoteAddress;
            inValue.NotesPassword = NotesPassword;
            SFC_Tools.ServiceReference1.SendGroupMailsWithAttachmentsResponse retVal = ((SFC_Tools.ServiceReference1.MessagingSoap)(this)).SendGroupMailsWithAttachments(inValue);
            return retVal.SendGroupMailsWithAttachmentsResult;
        }
    }
}
