//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.2034.
// 
#pragma warning disable 1591

namespace YZD.Schedule.TiptopService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private TPSoap tPSoapValueField;
        
        private System.Threading.SendOrPostCallback QueryMateriaMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryMateriaMaster1OperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryMateriaMaster2OperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryStock1OperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryBomOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryBom1OperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryBom2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GoodsTransferBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback GoodsBillDownloadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChargeBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChargeReturnBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryWorkOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GoodsBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback GoodsReturnBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback FinishedGoodsBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloseWorkOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateWorkOrderOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::YZD.Schedule.Properties.Settings.Default.YZD_Schedule_MESJob_TiptopService_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public TPSoap TPSoapValue {
            get {
                return this.tPSoapValueField;
            }
            set {
                this.tPSoapValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event QueryMateriaMasterCompletedEventHandler QueryMateriaMasterCompleted;
        
        /// <remarks/>
        public event QueryMateriaMaster1CompletedEventHandler QueryMateriaMaster1Completed;
        
        /// <remarks/>
        public event QueryMateriaMaster2CompletedEventHandler QueryMateriaMaster2Completed;
        
        /// <remarks/>
        public event QueryStockCompletedEventHandler QueryStockCompleted;
        
        /// <remarks/>
        public event QueryStock1CompletedEventHandler QueryStock1Completed;
        
        /// <remarks/>
        public event QueryBomCompletedEventHandler QueryBomCompleted;
        
        /// <remarks/>
        public event QueryBom1CompletedEventHandler QueryBom1Completed;
        
        /// <remarks/>
        public event QueryBom2CompletedEventHandler QueryBom2Completed;
        
        /// <remarks/>
        public event GoodsTransferBillCompletedEventHandler GoodsTransferBillCompleted;
        
        /// <remarks/>
        public event GoodsBillDownloadCompletedEventHandler GoodsBillDownloadCompleted;
        
        /// <remarks/>
        public event ChargeBillCompletedEventHandler ChargeBillCompleted;
        
        /// <remarks/>
        public event ChargeReturnBillCompletedEventHandler ChargeReturnBillCompleted;
        
        /// <remarks/>
        public event QueryWorkOrderCompletedEventHandler QueryWorkOrderCompleted;
        
        /// <remarks/>
        public event GoodsBillCompletedEventHandler GoodsBillCompleted;
        
        /// <remarks/>
        public event GoodsReturnBillCompletedEventHandler GoodsReturnBillCompleted;
        
        /// <remarks/>
        public event FinishedGoodsBillCompletedEventHandler FinishedGoodsBillCompleted;
        
        /// <remarks/>
        public event CloseWorkOrderCompletedEventHandler CloseWorkOrderCompleted;
        
        /// <remarks/>
        public event CreateWorkOrderCompletedEventHandler CreateWorkOrderCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryMateriaMaster", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut QueryMateriaMaster(string Client) {
            object[] results = this.Invoke("QueryMateriaMaster", new object[] {
                        Client});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void QueryMateriaMasterAsync(string Client) {
            this.QueryMateriaMasterAsync(Client, null);
        }
        
        /// <remarks/>
        public void QueryMateriaMasterAsync(string Client, object userState) {
            if ((this.QueryMateriaMasterOperationCompleted == null)) {
                this.QueryMateriaMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryMateriaMasterOperationCompleted);
            }
            this.InvokeAsync("QueryMateriaMaster", new object[] {
                        Client}, this.QueryMateriaMasterOperationCompleted, userState);
        }
        
        private void OnQueryMateriaMasterOperationCompleted(object arg) {
            if ((this.QueryMateriaMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryMateriaMasterCompleted(this, new QueryMateriaMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryMateriaMaster1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut QueryMateriaMaster1(string Client, System.DateTime dtbegin) {
            object[] results = this.Invoke("QueryMateriaMaster1", new object[] {
                        Client,
                        dtbegin});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void QueryMateriaMaster1Async(string Client, System.DateTime dtbegin) {
            this.QueryMateriaMaster1Async(Client, dtbegin, null);
        }
        
        /// <remarks/>
        public void QueryMateriaMaster1Async(string Client, System.DateTime dtbegin, object userState) {
            if ((this.QueryMateriaMaster1OperationCompleted == null)) {
                this.QueryMateriaMaster1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryMateriaMaster1OperationCompleted);
            }
            this.InvokeAsync("QueryMateriaMaster1", new object[] {
                        Client,
                        dtbegin}, this.QueryMateriaMaster1OperationCompleted, userState);
        }
        
        private void OnQueryMateriaMaster1OperationCompleted(object arg) {
            if ((this.QueryMateriaMaster1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryMateriaMaster1Completed(this, new QueryMateriaMaster1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryMateriaMaster2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut QueryMateriaMaster2(string Client, string PartNo) {
            object[] results = this.Invoke("QueryMateriaMaster2", new object[] {
                        Client,
                        PartNo});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void QueryMateriaMaster2Async(string Client, string PartNo) {
            this.QueryMateriaMaster2Async(Client, PartNo, null);
        }
        
        /// <remarks/>
        public void QueryMateriaMaster2Async(string Client, string PartNo, object userState) {
            if ((this.QueryMateriaMaster2OperationCompleted == null)) {
                this.QueryMateriaMaster2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryMateriaMaster2OperationCompleted);
            }
            this.InvokeAsync("QueryMateriaMaster2", new object[] {
                        Client,
                        PartNo}, this.QueryMateriaMaster2OperationCompleted, userState);
        }
        
        private void OnQueryMateriaMaster2OperationCompleted(object arg) {
            if ((this.QueryMateriaMaster2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryMateriaMaster2Completed(this, new QueryMateriaMaster2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut QueryStock(string Client, string warehouse) {
            object[] results = this.Invoke("QueryStock", new object[] {
                        Client,
                        warehouse});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void QueryStockAsync(string Client, string warehouse) {
            this.QueryStockAsync(Client, warehouse, null);
        }
        
        /// <remarks/>
        public void QueryStockAsync(string Client, string warehouse, object userState) {
            if ((this.QueryStockOperationCompleted == null)) {
                this.QueryStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryStockOperationCompleted);
            }
            this.InvokeAsync("QueryStock", new object[] {
                        Client,
                        warehouse}, this.QueryStockOperationCompleted, userState);
        }
        
        private void OnQueryStockOperationCompleted(object arg) {
            if ((this.QueryStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryStockCompleted(this, new QueryStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryStock1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut QueryStock1(string Client, string warehouse, string partno) {
            object[] results = this.Invoke("QueryStock1", new object[] {
                        Client,
                        warehouse,
                        partno});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void QueryStock1Async(string Client, string warehouse, string partno) {
            this.QueryStock1Async(Client, warehouse, partno, null);
        }
        
        /// <remarks/>
        public void QueryStock1Async(string Client, string warehouse, string partno, object userState) {
            if ((this.QueryStock1OperationCompleted == null)) {
                this.QueryStock1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryStock1OperationCompleted);
            }
            this.InvokeAsync("QueryStock1", new object[] {
                        Client,
                        warehouse,
                        partno}, this.QueryStock1OperationCompleted, userState);
        }
        
        private void OnQueryStock1OperationCompleted(object arg) {
            if ((this.QueryStock1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryStock1Completed(this, new QueryStock1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryBom", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut QueryBom(string Client) {
            object[] results = this.Invoke("QueryBom", new object[] {
                        Client});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void QueryBomAsync(string Client) {
            this.QueryBomAsync(Client, null);
        }
        
        /// <remarks/>
        public void QueryBomAsync(string Client, object userState) {
            if ((this.QueryBomOperationCompleted == null)) {
                this.QueryBomOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryBomOperationCompleted);
            }
            this.InvokeAsync("QueryBom", new object[] {
                        Client}, this.QueryBomOperationCompleted, userState);
        }
        
        private void OnQueryBomOperationCompleted(object arg) {
            if ((this.QueryBomCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryBomCompleted(this, new QueryBomCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryBom1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut QueryBom1(string Client, System.DateTime dtbegin) {
            object[] results = this.Invoke("QueryBom1", new object[] {
                        Client,
                        dtbegin});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void QueryBom1Async(string Client, System.DateTime dtbegin) {
            this.QueryBom1Async(Client, dtbegin, null);
        }
        
        /// <remarks/>
        public void QueryBom1Async(string Client, System.DateTime dtbegin, object userState) {
            if ((this.QueryBom1OperationCompleted == null)) {
                this.QueryBom1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryBom1OperationCompleted);
            }
            this.InvokeAsync("QueryBom1", new object[] {
                        Client,
                        dtbegin}, this.QueryBom1OperationCompleted, userState);
        }
        
        private void OnQueryBom1OperationCompleted(object arg) {
            if ((this.QueryBom1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryBom1Completed(this, new QueryBom1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryBom2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut QueryBom2(string Client, string pn) {
            object[] results = this.Invoke("QueryBom2", new object[] {
                        Client,
                        pn});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void QueryBom2Async(string Client, string pn) {
            this.QueryBom2Async(Client, pn, null);
        }
        
        /// <remarks/>
        public void QueryBom2Async(string Client, string pn, object userState) {
            if ((this.QueryBom2OperationCompleted == null)) {
                this.QueryBom2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryBom2OperationCompleted);
            }
            this.InvokeAsync("QueryBom2", new object[] {
                        Client,
                        pn}, this.QueryBom2OperationCompleted, userState);
        }
        
        private void OnQueryBom2OperationCompleted(object arg) {
            if ((this.QueryBom2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryBom2Completed(this, new QueryBom2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GoodsTransferBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut GoodsTransferBill(string Client, string BillHead, System.DateTime BillDate) {
            object[] results = this.Invoke("GoodsTransferBill", new object[] {
                        Client,
                        BillHead,
                        BillDate});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void GoodsTransferBillAsync(string Client, string BillHead, System.DateTime BillDate) {
            this.GoodsTransferBillAsync(Client, BillHead, BillDate, null);
        }
        
        /// <remarks/>
        public void GoodsTransferBillAsync(string Client, string BillHead, System.DateTime BillDate, object userState) {
            if ((this.GoodsTransferBillOperationCompleted == null)) {
                this.GoodsTransferBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGoodsTransferBillOperationCompleted);
            }
            this.InvokeAsync("GoodsTransferBill", new object[] {
                        Client,
                        BillHead,
                        BillDate}, this.GoodsTransferBillOperationCompleted, userState);
        }
        
        private void OnGoodsTransferBillOperationCompleted(object arg) {
            if ((this.GoodsTransferBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GoodsTransferBillCompleted(this, new GoodsTransferBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GoodsBillDownload", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut GoodsBillDownload(string Client, string BillHead, System.DateTime BillDate) {
            object[] results = this.Invoke("GoodsBillDownload", new object[] {
                        Client,
                        BillHead,
                        BillDate});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void GoodsBillDownloadAsync(string Client, string BillHead, System.DateTime BillDate) {
            this.GoodsBillDownloadAsync(Client, BillHead, BillDate, null);
        }
        
        /// <remarks/>
        public void GoodsBillDownloadAsync(string Client, string BillHead, System.DateTime BillDate, object userState) {
            if ((this.GoodsBillDownloadOperationCompleted == null)) {
                this.GoodsBillDownloadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGoodsBillDownloadOperationCompleted);
            }
            this.InvokeAsync("GoodsBillDownload", new object[] {
                        Client,
                        BillHead,
                        BillDate}, this.GoodsBillDownloadOperationCompleted, userState);
        }
        
        private void OnGoodsBillDownloadOperationCompleted(object arg) {
            if ((this.GoodsBillDownloadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GoodsBillDownloadCompleted(this, new GoodsBillDownloadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChargeBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ChargeBill(string Client, string BillHead, System.DateTime BillDate) {
            object[] results = this.Invoke("ChargeBill", new object[] {
                        Client,
                        BillHead,
                        BillDate});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ChargeBillAsync(string Client, string BillHead, System.DateTime BillDate) {
            this.ChargeBillAsync(Client, BillHead, BillDate, null);
        }
        
        /// <remarks/>
        public void ChargeBillAsync(string Client, string BillHead, System.DateTime BillDate, object userState) {
            if ((this.ChargeBillOperationCompleted == null)) {
                this.ChargeBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChargeBillOperationCompleted);
            }
            this.InvokeAsync("ChargeBill", new object[] {
                        Client,
                        BillHead,
                        BillDate}, this.ChargeBillOperationCompleted, userState);
        }
        
        private void OnChargeBillOperationCompleted(object arg) {
            if ((this.ChargeBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChargeBillCompleted(this, new ChargeBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChargeReturnBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut ChargeReturnBill(string Client, string BillHead, System.DateTime BillDate) {
            object[] results = this.Invoke("ChargeReturnBill", new object[] {
                        Client,
                        BillHead,
                        BillDate});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void ChargeReturnBillAsync(string Client, string BillHead, System.DateTime BillDate) {
            this.ChargeReturnBillAsync(Client, BillHead, BillDate, null);
        }
        
        /// <remarks/>
        public void ChargeReturnBillAsync(string Client, string BillHead, System.DateTime BillDate, object userState) {
            if ((this.ChargeReturnBillOperationCompleted == null)) {
                this.ChargeReturnBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChargeReturnBillOperationCompleted);
            }
            this.InvokeAsync("ChargeReturnBill", new object[] {
                        Client,
                        BillHead,
                        BillDate}, this.ChargeReturnBillOperationCompleted, userState);
        }
        
        private void OnChargeReturnBillOperationCompleted(object arg) {
            if ((this.ChargeReturnBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChargeReturnBillCompleted(this, new ChargeReturnBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryWorkOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut QueryWorkOrder(string Client, string WorkOrder) {
            object[] results = this.Invoke("QueryWorkOrder", new object[] {
                        Client,
                        WorkOrder});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void QueryWorkOrderAsync(string Client, string WorkOrder) {
            this.QueryWorkOrderAsync(Client, WorkOrder, null);
        }
        
        /// <remarks/>
        public void QueryWorkOrderAsync(string Client, string WorkOrder, object userState) {
            if ((this.QueryWorkOrderOperationCompleted == null)) {
                this.QueryWorkOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryWorkOrderOperationCompleted);
            }
            this.InvokeAsync("QueryWorkOrder", new object[] {
                        Client,
                        WorkOrder}, this.QueryWorkOrderOperationCompleted, userState);
        }
        
        private void OnQueryWorkOrderOperationCompleted(object arg) {
            if ((this.QueryWorkOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryWorkOrderCompleted(this, new QueryWorkOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GoodsBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut GoodsBill(string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin) {
            object[] results = this.Invoke("GoodsBill", new object[] {
                        Client,
                        BillHead,
                        WorkOrder,
                        PartNo,
                        Qty,
                        Warehouse,
                        Bin});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void GoodsBillAsync(string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin) {
            this.GoodsBillAsync(Client, BillHead, WorkOrder, PartNo, Qty, Warehouse, Bin, null);
        }
        
        /// <remarks/>
        public void GoodsBillAsync(string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin, object userState) {
            if ((this.GoodsBillOperationCompleted == null)) {
                this.GoodsBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGoodsBillOperationCompleted);
            }
            this.InvokeAsync("GoodsBill", new object[] {
                        Client,
                        BillHead,
                        WorkOrder,
                        PartNo,
                        Qty,
                        Warehouse,
                        Bin}, this.GoodsBillOperationCompleted, userState);
        }
        
        private void OnGoodsBillOperationCompleted(object arg) {
            if ((this.GoodsBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GoodsBillCompleted(this, new GoodsBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GoodsReturnBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut GoodsReturnBill(string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin) {
            object[] results = this.Invoke("GoodsReturnBill", new object[] {
                        Client,
                        BillHead,
                        WorkOrder,
                        PartNo,
                        Qty,
                        Warehouse,
                        Bin});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void GoodsReturnBillAsync(string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin) {
            this.GoodsReturnBillAsync(Client, BillHead, WorkOrder, PartNo, Qty, Warehouse, Bin, null);
        }
        
        /// <remarks/>
        public void GoodsReturnBillAsync(string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin, object userState) {
            if ((this.GoodsReturnBillOperationCompleted == null)) {
                this.GoodsReturnBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGoodsReturnBillOperationCompleted);
            }
            this.InvokeAsync("GoodsReturnBill", new object[] {
                        Client,
                        BillHead,
                        WorkOrder,
                        PartNo,
                        Qty,
                        Warehouse,
                        Bin}, this.GoodsReturnBillOperationCompleted, userState);
        }
        
        private void OnGoodsReturnBillOperationCompleted(object arg) {
            if ((this.GoodsReturnBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GoodsReturnBillCompleted(this, new GoodsReturnBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FinishedGoodsBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut FinishedGoodsBill(string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin) {
            object[] results = this.Invoke("FinishedGoodsBill", new object[] {
                        Client,
                        BillHead,
                        WorkOrder,
                        PartNo,
                        Qty,
                        Warehouse,
                        Bin});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void FinishedGoodsBillAsync(string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin) {
            this.FinishedGoodsBillAsync(Client, BillHead, WorkOrder, PartNo, Qty, Warehouse, Bin, null);
        }
        
        /// <remarks/>
        public void FinishedGoodsBillAsync(string Client, string BillHead, string WorkOrder, string PartNo, decimal Qty, string Warehouse, string Bin, object userState) {
            if ((this.FinishedGoodsBillOperationCompleted == null)) {
                this.FinishedGoodsBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFinishedGoodsBillOperationCompleted);
            }
            this.InvokeAsync("FinishedGoodsBill", new object[] {
                        Client,
                        BillHead,
                        WorkOrder,
                        PartNo,
                        Qty,
                        Warehouse,
                        Bin}, this.FinishedGoodsBillOperationCompleted, userState);
        }
        
        private void OnFinishedGoodsBillOperationCompleted(object arg) {
            if ((this.FinishedGoodsBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FinishedGoodsBillCompleted(this, new FinishedGoodsBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TPSoapValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CloseWorkOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut CloseWorkOrder(string Client, string WorkOrder) {
            object[] results = this.Invoke("CloseWorkOrder", new object[] {
                        Client,
                        WorkOrder});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void CloseWorkOrderAsync(string Client, string WorkOrder) {
            this.CloseWorkOrderAsync(Client, WorkOrder, null);
        }
        
        /// <remarks/>
        public void CloseWorkOrderAsync(string Client, string WorkOrder, object userState) {
            if ((this.CloseWorkOrderOperationCompleted == null)) {
                this.CloseWorkOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloseWorkOrderOperationCompleted);
            }
            this.InvokeAsync("CloseWorkOrder", new object[] {
                        Client,
                        WorkOrder}, this.CloseWorkOrderOperationCompleted, userState);
        }
        
        private void OnCloseWorkOrderOperationCompleted(object arg) {
            if ((this.CloseWorkOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloseWorkOrderCompleted(this, new CloseWorkOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateWorkOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceOut CreateWorkOrder(string Client, string BillHead, string DeptCode, string PartNo, decimal Qty, System.DateTime StartDate, System.DateTime EndDate) {
            object[] results = this.Invoke("CreateWorkOrder", new object[] {
                        Client,
                        BillHead,
                        DeptCode,
                        PartNo,
                        Qty,
                        StartDate,
                        EndDate});
            return ((ServiceOut)(results[0]));
        }
        
        /// <remarks/>
        public void CreateWorkOrderAsync(string Client, string BillHead, string DeptCode, string PartNo, decimal Qty, System.DateTime StartDate, System.DateTime EndDate) {
            this.CreateWorkOrderAsync(Client, BillHead, DeptCode, PartNo, Qty, StartDate, EndDate, null);
        }
        
        /// <remarks/>
        public void CreateWorkOrderAsync(string Client, string BillHead, string DeptCode, string PartNo, decimal Qty, System.DateTime StartDate, System.DateTime EndDate, object userState) {
            if ((this.CreateWorkOrderOperationCompleted == null)) {
                this.CreateWorkOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateWorkOrderOperationCompleted);
            }
            this.InvokeAsync("CreateWorkOrder", new object[] {
                        Client,
                        BillHead,
                        DeptCode,
                        PartNo,
                        Qty,
                        StartDate,
                        EndDate}, this.CreateWorkOrderOperationCompleted, userState);
        }
        
        private void OnCreateWorkOrderOperationCompleted(object arg) {
            if ((this.CreateWorkOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateWorkOrderCompleted(this, new CreateWorkOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.2022")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class TPSoap : System.Web.Services.Protocols.SoapHeader {
        
        private string userIDField;
        
        private string userPWDField;
        
        private string ipAddressField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserPWD {
            get {
                return this.userPWDField;
            }
            set {
                this.userPWDField = value;
            }
        }
        
        /// <remarks/>
        public string IpAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.2022")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BackRes {
        
        private string[] arrstrresField;
        
        private System.Data.DataTable workorderdetailField;
        
        /// <remarks/>
        public string[] arrstrres {
            get {
                return this.arrstrresField;
            }
            set {
                this.arrstrresField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable workorderdetail {
            get {
                return this.workorderdetailField;
            }
            set {
                this.workorderdetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.2022")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceOut {
        
        private BackRes backresField;
        
        private string statusField;
        
        private System.Data.DataTable tableInfoField;
        
        private System.Data.DataSet setInfoField;
        
        private string[] arrayInfoField;
        
        private string messageField;
        
        private string errorField;
        
        /// <remarks/>
        public BackRes Backres {
            get {
                return this.backresField;
            }
            set {
                this.backresField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable TableInfo {
            get {
                return this.tableInfoField;
            }
            set {
                this.tableInfoField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet SetInfo {
            get {
                return this.setInfoField;
            }
            set {
                this.setInfoField = value;
            }
        }
        
        /// <remarks/>
        public string[] ArrayInfo {
            get {
                return this.arrayInfoField;
            }
            set {
                this.arrayInfoField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryMateriaMasterCompletedEventHandler(object sender, QueryMateriaMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryMateriaMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryMateriaMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryMateriaMaster1CompletedEventHandler(object sender, QueryMateriaMaster1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryMateriaMaster1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryMateriaMaster1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryMateriaMaster2CompletedEventHandler(object sender, QueryMateriaMaster2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryMateriaMaster2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryMateriaMaster2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryStockCompletedEventHandler(object sender, QueryStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryStock1CompletedEventHandler(object sender, QueryStock1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryStock1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryStock1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryBomCompletedEventHandler(object sender, QueryBomCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryBomCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryBomCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryBom1CompletedEventHandler(object sender, QueryBom1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryBom1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryBom1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryBom2CompletedEventHandler(object sender, QueryBom2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryBom2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryBom2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GoodsTransferBillCompletedEventHandler(object sender, GoodsTransferBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GoodsTransferBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GoodsTransferBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GoodsBillDownloadCompletedEventHandler(object sender, GoodsBillDownloadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GoodsBillDownloadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GoodsBillDownloadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ChargeBillCompletedEventHandler(object sender, ChargeBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChargeBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChargeBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ChargeReturnBillCompletedEventHandler(object sender, ChargeReturnBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChargeReturnBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChargeReturnBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void QueryWorkOrderCompletedEventHandler(object sender, QueryWorkOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryWorkOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryWorkOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GoodsBillCompletedEventHandler(object sender, GoodsBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GoodsBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GoodsBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GoodsReturnBillCompletedEventHandler(object sender, GoodsReturnBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GoodsReturnBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GoodsReturnBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FinishedGoodsBillCompletedEventHandler(object sender, FinishedGoodsBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FinishedGoodsBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FinishedGoodsBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CloseWorkOrderCompletedEventHandler(object sender, CloseWorkOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloseWorkOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CloseWorkOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreateWorkOrderCompletedEventHandler(object sender, CreateWorkOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateWorkOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateWorkOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceOut Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceOut)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591