//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFC_Tools.ServiceReference3 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.AccreditInfoSoap")]
    public interface AccreditInfoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAccreditInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAccreditInfo(string userid, string pwd, string empno, string empname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getEcardInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getEcardInfo(string userid, string pwd, string empno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetResignedEployeesInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetResignedEployeesInfo(string startDate, string endDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccreditInfoSoapChannel : SFC_Tools.ServiceReference3.AccreditInfoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccreditInfoSoapClient : System.ServiceModel.ClientBase<SFC_Tools.ServiceReference3.AccreditInfoSoap>, SFC_Tools.ServiceReference3.AccreditInfoSoap {
        
        public AccreditInfoSoapClient() {
        }
        
        public AccreditInfoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccreditInfoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccreditInfoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccreditInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getAccreditInfo(string userid, string pwd, string empno, string empname) {
            return base.Channel.getAccreditInfo(userid, pwd, empno, empname);
        }
        
        public System.Data.DataSet getEcardInfo(string userid, string pwd, string empno) {
            return base.Channel.getEcardInfo(userid, pwd, empno);
        }
        
        public System.Data.DataSet GetResignedEployeesInfo(string startDate, string endDate) {
            return base.Channel.GetResignedEployeesInfo(startDate, endDate);
        }
    }
}
